%YAML:1.0

CannyEdge.threshold1: 80
CannyEdge.threshold2: 200
CannyEdge.apertureSize: 5
CannyEdge.L2gradient: 0

HoughLinesP.rho: 1
HoughLinesP.theta: 0.01745329251 # pi/180
HoughLinesP.threshold: 120
HoughLinesP.minLineLength: 40
HoughLinesP.maxLineGap: 40